language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
branches:
  only:
    - master
install:
  - pip install SpeechRecognition flake8 pytest
  - pip install .
script:
  - flake8 ./
  - py.test ./
